server:
    servlet:
        context-path: /cadastra-usuario/api

#spring:
#  datasource:
#    url: jdbc:localhost:3307
#    username: sa
#    password:
#    driverClassName: org.h2.Driver

spring:
  datasource:
    url: jdbc:postgresql://localhost:3306/postgres
    username: postgres
    password:
    driverClassName: org.postgresql.Driver

#    h2:
#      console:
#        enabled: true
#        path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create